name: Build and test all platforms
on:
  push:
    paths-ignore:
      - '**.md'
      - .clang-format
      - .gitignore
  workflow_dispatch:

jobs:
  linux:
    permissions:
      contents: read
    uses: ./.github/workflows/linux.yml

  # macos:
  #   permissions:
  #     contents: read
  #   uses: ./.github/workflows/macos.yml

  # windows:
  #   permissions:
  #     contents: read
  #   uses: ./.github/workflows/windows.yml
